server:
  port: 9000

logging:
  level:
    root: DEBUG
#    org.springframework.web: INFO
#    org.springframework.security: I
#    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
debug: true
